### ISSUE TITLE
Add support for older versions of react query

### ISSUE THREAD

**Issue by lavocatt** [7nohe/openapi-react-query-codegen#100]
**Is your feature request related to a problem? Please describe.**

The product I'm working on is integrating in a federation of React components. See https://github.com/openshift/dynamic-plugin-sdk Which means that I can't chose the version of React I'm working with. Right now OpenShift console runs React 17. In turn this means that we have to use react-query at version 4.

**Describe the solution you'd like**

I'd love the codegen executable to accept a parameter to specify which version of react-query to use for the generation.

**Describe alternatives you've considered**

ATM, to overcome this issue I'm running your codegen solution in it's version `0.4.1`. While it's been working great, it also means that I would miss on any new cool features you are implementing.

**Comment by seriouslag** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> 
> 
> The product I'm working on is integrating in a federation of React components. See https://github.com/openshift/dynamic-plugin-sdk Which means that I can't chose the version of React I'm working with. Right now OpenShift console runs React 17. In turn this means that we have to use react-query at version 4.
> 
> 
> 
> **Describe the solution you'd like**
> 
> 
> 
> I'd love the codegen executable to accept a parameter to specify which version of react-query to use for the generation.
> 
> 
> 
> **Describe alternatives you've considered**
> 
> 
> 
> ATM, to overcome this issue I'm running your codegen solution in it's version `0.4.1`. While it's been working great, it also means that I would miss on any new cool features you are implementing.
> 
> 
> 
> 

While that would be nice, there is no way for us to support older version as the types do not match. Feel free to fork and back port features. I suggest opening tickets with your out of date code.
