### ISSUE TITLE
"error TS6133: 'queryKey' is declared but its value is never read" from queries.ts and suspense.ts

### ISSUE THREAD

**Issue by Etsija** [7nohe/openapi-react-query-codegen#112]
**Describe the bug**
Files `queries/queries.ts` and `queries/suspense.ts` generate TS errors from `queryKey` being declared but its value never read, resulting in error TS6133 when building a project with the API.

**OpenAPI JSON causing the bug**
[api.json](https://github.com/7nohe/openapi-react-query-codegen/files/15294060/api.json)

**Expected behavior**
Either don't generate unused parameters, or auto-insert 
```
// @ts-nocheck
```
to generated files which may declare unused variables.

- OS: Ubuntu 22.04
- Version 1.3.0

**Comment by sschuberth** [comment]
Does this report, just [like mine](https://github.com/7nohe/openapi-react-query-codegen/issues/111#issuecomment-2106250632), need to go to upstream https://github.com/hey-api/openapi-ts as well?

**Comment by Etsija** [comment]
I'd like an answer to the question above, as we need a fix to this issue, and need to know whether we should create a ticket upstream.

**Comment by seriouslag** [comment]
This is a bug. `queryKey` should always be used.
The issue is that when there are no parameters for a request, then the queryKey is not used in the hook; this is incorrect.
We should be using the provided queryKey if it is provided.

**Comment by Etsija** [comment]
Thanks for the reply, I will be following this issue to see when a proper fix is implemented so we can remove our workarounds for it.
