### ISSUE TITLE
Fail to generate the queries of Camunda 7 openapi.yaml

### ISSUE THREAD

**Issue by sac-varadise** [7nohe/openapi-react-query-codegen#113]
**Describe the bug**
I tried to generate the client with Camunda 7 openapi.yaml but it's failed via creating the queries.

**To Reproduce**
Run the following command with the provided openapi.yaml
`openapi-rq -i ./openapi.yaml -o ./client -c axios --format prettier --debug`

**OpenAPI spec file**
[openapi.yaml.zip](https://github.com/7nohe/openapi-react-query-codegen/files/15307422/openapi.yaml.zip)

**Expected behavior**
`requests` and `queries` folder code generate successfully.

- OS: macOS
- Version 14.4.1 (23E224)

**Comment by seriouslag** [comment]
Please provide an openapi spec file or a link to one.

**Comment by sac-varadise** [comment]
> Please provide an openapi spec file or a link to one.

The openapi.yaml was attached in the middle of the issue - `OpenAPI spec file`

> **Describe the bug** I tried to generate the client with Camunda 7 openapi.yaml but it's failed via creating the queries.
> 
> **To Reproduce** Run the following command with the provided openapi.yaml `openapi-rq -i ./openapi.yaml -o ./client -c axios --format prettier --debug`
> 
> **OpenAPI spec file** [openapi.yaml.zip](https://github.com/7nohe/openapi-react-query-codegen/files/15307422/openapi.yaml.zip)
> 
> **Expected behavior** `requests` and `queries` folder code generate successfully.
> 
> * OS: macOS
> * Version 14.4.1 (23E224)

**Comment by seriouslag** [comment]
Thank you, i have reproduced an the issue with the file, seems the underlying service generator [@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts) is fails to handle the error descriptions.
