### ISSUE TITLE
Prettier not run on `api/queries`

### ISSUE THREAD

**Issue by sschuberth** [7nohe/openapi-react-query-codegen#114]
**Describe the bug**

With `--format prettier`, no formatting seems to happen for files generated in `api/queries`.

**To Reproduce**

Create a `.prettierrc` with some non-default formatting setting and run with `--format prettier`.

**OpenAPI spec file**

n/a

**Expected behavior**

File in `api/queries` should get formatted just like the ones in `api/requests` do.

**Screenshots**

n/a

- OS: Linux and Windows
- Version: v1.3.0

**Additional context**

The effect can be seen in https://github.com/eclipse-apoapsis/ort-server/pull/224/files.

**Comment by seriouslag** [comment]
Prettier, eslint, or biome has to be listed a devDependency in the package.json or it will be silently ignored. A known issue. There are other open issues about this already.

**Comment by seriouslag** [comment]
@7nohe 
I am starting to believe we should remove the feature and let the consumers run linting and formatting as duplicating the work of the underlying service generator will be difficult to maintain parity as they do not expose it to other files.

A work around is running the pretter after running the service gen.

**Comment by 7nohe** [comment]
> @7nohe I am starting to believe we should remove the feature and let the consumers run linting and formatting as duplicating the work of the underlying service generator will be difficult to maintain parity as they do not expose it to other files.
> 
> A work around is running the pretter after running the service gen.

@seriouslag 
I agree with you. Typically, users do import the output and call functions, but they do not usually modify it. It is best to allow users to make any desired changes after the generation.

**Comment by sschuberth** [comment]
For the same reason as mentioned [here](https://github.com/7nohe/openapi-react-query-codegen/issues/111#issuecomment-2118734787), let's just close this in favor of removing the `--format` version going forward.
