### ISSUE TITLE
When generated the parameter of type "object" turns into type "unknown". Type "any" would be preferred.

### ISSUE THREAD

**Issue by hugokemme7** [7nohe/openapi-react-query-codegen#120]
it would be great if the type object would translate to type any instead of unknown. I cant use the type object right now, because when it transforms to unknown it gives me a ton of ts errors, wich would be solved if the type any would be used. Or maybe a way yo configure it would be nice.

**Comment by 7nohe** [comment]
@hugokemme7 
This library uses @hey-api/openapi-ts for type generation from the OpenAPI spec, so I recommend creating an issue [there](https://github.com/hey-api/openapi-ts/issues).
