### ISSUE TITLE
Query key different in generated prefetch.ts vs generated queries.ts

### ISSUE THREAD

**Issue by TomWebbio** [7nohe/openapi-react-query-codegen#121]
**Describe the bug**
I generated the files for nextjs approuter using fetch. I noticed the prefetch isnt working, because the queryKey is generated differently in the generated code, meaning that React-query think it's 2 different queries.

See the querykey in the prefetch.ts: 

`queryClient.prefetchQuery({
		queryKey: [
			Common.useQuestionairesServiceQuestionaireControllerFindKey,
			[{ filterId, limit, page, search, searchBy, sortBy }]
		],
		queryFn: () => QuestionairesService.questionaireControllerFind({ filterId, limit, page, search, searchBy, sortBy })
	});`

Now see the querykey in the queries.ts:

`useQuery<TData, TError>({
		queryKey: Common.UseQuestionairesServiceQuestionaireControllerFindKeyFn(
			{ filterId, limit, page, search, searchBy, sortBy },
			queryKey
		),
		queryFn: () =>
			QuestionairesService.questionaireControllerFind({ filterId, limit, page, search, searchBy, sortBy }) as TData,
		...options
	});`

This results in 2 different keys in queries: 
<img width="516" alt="image" src="https://github.com/7nohe/openapi-react-query-codegen/assets/48241143/33927b71-9296-4cec-8cbc-98012cbf3855">

**To Reproduce**

Generate the files using this script:

`"codegen": "rimraf ./openapi && openapi-rq -i https://our-url/api.json -c fetch && prettier --write .",`

I can easily fix this in the generated code by using the same querykey generation method in the queries.ts as in the prefetch.ts

If there's any way for you guys to fix this, or to give me a solid work around, that'd be great!

**Comment by 7nohe** [comment]
#102 is a duplicate. Currently working on #103.

**Comment by TomWebbio** [comment]
Thanks, I will close this issue and keep track of those.
