### ISSUE TITLE
Issue with Custom Request File Path

### ISSUE THREAD

**Issue by xalidmalik** [7nohe/openapi-react-query-codegen#124]
**Describe the bug**
The command specified in the options section is not functioning as expected. When I specify a different file path for the request option, it still defaults to using the request/core/request.ts file instead of the custom path provided.

**To Reproduce**

1. Execute the following command: openapi-rq -i ./openapi.json -c axios --request=./src/services/request.ts -o ./src/services --format=prettier --lint=eslint
2. Observe that the request file used is request/core/request.ts instead of the specified src/services/request.ts.

**OpenAPI spec file**
If possible, please upload the OpenAPI spec file.

**Expected behavior**
The command should use the specified custom request file path (src/services/request.ts) instead of defaulting to request/core/request.ts.

**Screenshots**
If applicable, add screenshots or logs to help explain your problem.

- OS: macOS
- Version: v1.4.0

**Additional context**
The specified command is:

`"codegen": "openapi-rq -i ./openapi.json -c axios --request=./src/services/request.ts -o ./src/services --format=prettier --lint=eslint"
`

Even if I specify a different file path for the request option, it defaults to using request/core/request.ts.

Thank you to the maintainer for this awesome and helpful library! It has been incredibly useful in our projects.

**Comment by seriouslag** [comment]
The custom request file is copied from the provided request file location to request/core/request.ts

When you want to edit the request file you must rerun the generator for the updates to be copied into the generated files.

I wouldn’t manually edit the generated files, unless you are committing them.
