### ISSUE TITLE
Support customizing `initialPageParam`

### ISSUE THREAD

**Issue by adamgoose** [7nohe/openapi-react-query-codegen#141]
**Is your feature request related to a problem? Please describe.**
The newly added Infinite Query support generates a hard-coded `initialPageParam: 1`. This prevents use with cursor-based or zero-indexed pagination APIs.

**Describe the solution you'd like**
Support customizing the `initialPageParam`, be it null, string, or number.

**Describe alternatives you've considered**
I'll have to manually define the infinite query in the meantime, utilizing the generated API client.

**Comment by 7nohe** [comment]
It should have been resolved in v1.6.1.

**Comment by ekuzu** [comment]
Hi Guys

I uses 1.6.1, if i don't set initialPageParam in cli, It sends query page param as "initialPageParam" rather then default value 1

api/customers?**page=initialPageParam**&limit=10&search=

**Comment by 7nohe** [comment]
> Hi Guys
> 
> I uses 1.6.1, if i don't set initialPageParam in cli, It sends query page param as "initialPageParam" rather then default value 1
> 
> api/customers?**page=initialPageParam**&limit=10&search=
> 
> If it works like this please update the README
> 
> Thanks.


The issue is expected to be resolved in #149.
