### ISSUE TITLE
Support nested `nextPageParam` values

### ISSUE THREAD

**Issue by adamgoose** [7nohe/openapi-react-query-codegen#142]
**Is your feature request related to a problem? Please describe.**
My API returns the `nextPageParam` as `meta.next`. Passing `--nextPageParam meta.next` results in broken typescript generation as local variables don't support dots.

```ts
getNextPageParam: response => (response as { meta.next: number }).meta.next
```

**Describe the solution you'd like**
Support dots in the `nextPageParam` name and traverse the response accordingly.

**Describe alternatives you've considered**
I'll have to manually define the infinite query in the meantime, utilizing the generated API client.

**Comment by 7nohe** [comment]
It should have been resolved in v1.6.1.
