### ISSUE TITLE
TError always unknown

### ISSUE THREAD

**Issue by Alexandre-Cornillon** [7nohe/openapi-react-query-codegen#147]
**Describe the bug**

Hello,
When we use the `TError` type from codegen, the type is always `unknown`.
How to have the payload or message of all the 400s and 500s errors typed ?
Thanks

**To Reproduce**
`npx --package @7nohe/openapi-react-query-codegen openapi-rq -i https://petstore.swagger.io/v2/swagger.json -o src/generated`

**OpenAPI spec file**
https://petstore.swagger.io/v2/swagger.json

**Expected behavior**
I need to have the content or message of all the 400s and 500s errors.

**Screenshots**
<img width="438" alt="Screenshot 2024-09-05 at 17 45 16" src="https://github.com/user-attachments/assets/123ff0a6-c8b7-4f97-93e1-a41659897034">

- OS: macOS
- Version: Sonoma 14.5

**Additional context**

**Comment by w00kie** [comment]
Facing the same issue, I don't know how to use error message in my returned data with the `onError` method.

My openapi.yml has definitions for error objects returned on 400 error code and these are picked up in the `types.gen.ts` file but I don't see how to use them in my mutate hooks.

**Comment by 7nohe** [comment]
From v2, TError is now typed.

```ts
export const useFindPets = <
  TData = Common.FindPetsDefaultResponse,
  TError = FindPetsError,
  TQueryKey extends Array<unknown> = unknown[],
>(
  clientOptions: Options<FindPetsData, true> = {},
  queryKey?: TQueryKey,
  options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">,
) =>
  useQuery<TData, TError>({
    queryKey: Common.UseFindPetsKeyFn(clientOptions, queryKey),
    queryFn: () =>
      findPets({ ...clientOptions }).then(
        (response) => response.data as TData,
      ) as TData,
    ...options,
  });
```
