### ISSUE TITLE
How to add refresh token logic?

### ISSUE THREAD

**Issue by karkigrishmin** [7nohe/openapi-react-query-codegen#152]
I'm using auto generated service.gen.ts and core.ts file. In layout.tsx file for passing token in header I have done like this:

```
  useEffect(() => {
    OpenAPI.interceptors.request.use((config) => {
      const { token } = getToken()

      config.headers = {
        Authorization: token ? `Bearer ${token}` : '',
      }
      return config
    })
  }, [])
```

Similarly, how to add refresh token logic?

cc: @7nohe

**Comment by 7nohe** [comment]
I believe you can use an interceptor for responses to add refresh token logic.

https://heyapi.vercel.app/openapi-ts/clients/fetch.html#interceptors
