### ISSUE TITLE
Duplicate endpoints create conflicting data types

### ISSUE THREAD

**Issue by CHE1RON** [7nohe/openapi-react-query-codegen#154]
**Describe the bug**
When having endpoints of the same name, eg `tags/{tag}/export` and `labels/{label}/export`, only one data type is generated (here `ExportData`) for all services, which is correct for the first, but wrong for all subsequent services.

**To Reproduce**
1. Create API with endpoints `tags/{tag}/export` and `labels/{label}/export`
2. Run script
3. Inspect type errors in `services.gen.ts` 

**OpenAPI spec file**
[routes.json](https://github.com/user-attachments/files/17189239/routes.json)

**Expected behavior**
Data types free of conflicts, eg `ExportData`, `ExportData1`, etc

**Screenshots**
If applicable, add screenshots or logs to help explain your problem.

- OS: macOS v14.4
- Version 1.6.3

**Comment by 7nohe** [comment]
`services.gen.ts` is a file generated on the [`@hey-api/openapi-ts`](https://heyapi.vercel.app/openapi-ts/get-started.html) side, so it falls outside the scope of this library.
This issue can likely be avoided by using [operationId](https://openapi-react-query-codegen.vercel.app/guides/cli-options#operationid).

**Comment by CHE1RON** [comment]
@7nohe Thanks for letting me know 🙏

I guess I'll open an issue upstream then. How exactly does `operationId` work? From the docs it seems to be a flag, but its default is `true` .. ?

**Comment by 7nohe** [comment]
@CHE1RON 
Yes, the default is true. Therefore, all you need to do is make each operationId unique.

```json
"paths": {
    "/api/v1/boards/export": {
      "get": {
        "tags": ["boards"],
        "summary": "Returns an export of a collection of boards.",
        "operationId": "boards-export",

   "/api/v1/documents/{file}/export": {
      "get": {
        "tags": ["documents"],
        "summary": "Exports the document as a PDF with annotations included.",
        "operationId": "documents-export",
```

**Comment by CHE1RON** [comment]
Right, but I'm referencing the URL to the JSON spec file, not a local `yml` file 🤔
