### ISSUE TITLE
Respect deprecated properties

### ISSUE THREAD

**Issue by seriouslag** [7nohe/openapi-react-query-codegen#18]
It would be nice if the generated hooks that were listed as depreciated in the OpenAPI spec had a JSDoc `@deprecated` comment.

**Comment by 7nohe** [comment]
`@deprecated` comment is also attached to the code generated by openapi-typescript-codegen, so it seems possible to reuse them.

**Comment by 7nohe** [comment]
This has been resolved in v0.5.2.
