### ISSUE TITLE
Error '.requiredOption is not a function'

### ISSUE THREAD

**Issue by silenzium** [7nohe/openapi-react-query-codegen#19]
I just installed and tested but get the following error:

```
 openapi-rq --input http://localhost:8082/docs/openapi.yaml -o src/services/openapi
C:\Users\...\node_modules\@7nohe\openapi-react-query-codegen\dist\src\cli.js:15
    .requiredOption("-i, --input <value>", "OpenAPI specification, can be a path, url or string content (required)")
     ^

TypeError: program.name(...).version(...).description(...).requiredOption is not a function
    at Object.<anonymous> (C:\Users\...\node_modules\@7nohe\openapi-react-query-codegen\dist\src\cli.js:15:6)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.15.0
error Command failed with exit code 1.
```

I tried with Node version 16 before, same issue.
I am on windows 11. 
JFYI: generating code with `openapi-typescript-codegen` works in this project.

Thanks for any advice.

**Comment by 7nohe** [comment]
@silenzium I found that this error occurs if an older version of commander.js is installed. Could you please try installing the newer version?

**Comment by nopitown** [comment]
Running into the same issue, isn't commander a direct dependency of this package?

**Comment by seriouslag** [comment]
We may need to set a minimum node version as Commander is a peer dep and only recent node versions pull in peer deps.

**Comment by nopitown** [comment]
I fixed this issue by setting commander with a major version.

**Comment by silenzium** [comment]
Thanks, got it running adding `"commander": "^10.0.0"` to resolutions in package.json
