### ISSUE TITLE
Not working with NextJS

### ISSUE THREAD

**Issue by Mexflubber** [7nohe/openapi-react-query-codegen#24]
Hi,

Any idea why the example is not working with NextJSs pages router?

I see the network call and the browser is receiving the data but nothing renders.

Thanks

**Comment by Mexflubber** [comment]
Note. I did a quick test using app router and this is working server side but not client side so re-fetching is not possible.

**Comment by 7nohe** [comment]
@Mexflubber As you mentioned, because Next.js uses SSR, you might need `getStaticProps()` for initial data fetching.
Please check out the following.
https://tanstack.com/query/v4/docs/react/guides/ssr#using-nextjs
