### ISSUE TITLE
Return types of query results

### ISSUE THREAD

**Issue by TimoVaassen** [7nohe/openapi-react-query-codegen#32]
It would be great if the return type of a generated useQuery were automatically exported, making it easier for me to use them in my own interfaces. Since the recent update you released, the return type of a query is, for example, Omit<useQueryResult<type, unknown>, "data"> & { data: TData }, which is fantastic because it allows us to override the return type. However, it now requires me to adjust all my code to accommodate the 'omit' variant, and 'UseQueryResult<type, unknown>' is no longer valid.

**Comment by 7nohe** [comment]
This has been resolved in v0.5.2.
