### ISSUE TITLE
How to specify basepath url?

### ISSUE THREAD

**Issue by smart-atresnjo** [7nohe/openapi-react-query-codegen#41]
Hey, thanks for the work on the package, pretty useful!

Had a question regarding generating a different BASE url property based on the running env.

export const OpenAPI: OpenAPIConfig = {
    BASE: 'https://my.staging.api.com,
}

On dev we are accessing the generated API staging env
On prod we are accessing the generated API prod env

For prod we'd like to generate 

export const OpenAPI: OpenAPIConfig = {
    BASE: 'https://my.api.com,
}

It's the same API, just a different BASE url. 👍 

Thanks!

**Comment by seriouslag** [comment]
I'm on mobile right now but there are a few ways to handle this but each would involve passing the env url as a parameter in runtime and not at generation. You can pass the baseUrl into the base request. Look at the example provided in the repo where they are using axios. You can override the base there. This can also be done with fetch.

**Comment by smart-atresnjo** [comment]
I see, so using request.ts as the template for the code generation, but the issue is that I am generating 3 different API clients, how do I specify a request.ts for one specific client?

**Comment by smart-atresnjo** [comment]
thanks, it worked!

baseURL: import.meta.env.VITE_API_URL
