### ISSUE TITLE
Upgrade to v.0.26.0 of openapi-typescript-codegen

### ISSUE THREAD

**Issue by andrecarrblad** [7nohe/openapi-react-query-codegen#42]
Hi,

A new version of openapi-typescript-codegen is available (v.0.26.0), which includes upgraded dependencies. This update specifically addresses a warning related to deprecated usage of json-schema-ref-parser.

Previously, the codebase was triggering the following warning:
npm WARN deprecated json-schema-ref-parser@9.0.9: Please switch to @apidevtools/json-schema-ref-parser

Best regards,
André

**Comment by AnderssonPeter** [comment]
@7nohe is there any reason this has not been done? if not would you accept a PR?

**Comment by 7nohe** [comment]
I tried upgrading to v0.26.0 once, but it was failing [the Windows test](https://github.com/7nohe/openapi-react-query-codegen/actions/runs/7775128279/job/21200735622), so I reverted back to v0.25.0. It seems that v0.27.0 has been released, so I would like to try it again.

**Comment by 7nohe** [comment]
I created a PR, but the Windows test still failed.
It seems there is an issue with json-schema-ref-parser regarding Windows.
https://github.com/APIDevTools/json-schema-ref-parser/issues/303

**Comment by AnderssonPeter** [comment]
What happens if you change `node ../../dist/src/cli.js -i ./petstore.yaml -c axios --exportSchemas=true --postfixServices=Client --request ./request.ts` to `node ../../dist/src/cli.js -i petstore.yaml -c axios --exportSchemas=true --postfixServices=Client --request request.ts`?
Also the path seperators here are linux not windows, unsure if that is a problem or not.

**Comment by 7nohe** [comment]
@AnderssonPeter I tried it, but it didn't work.

**Comment by AnderssonPeter** [comment]
@7nohe I tried to run it locally and the file does not exist in the location that it looks for it.
![image](https://github.com/7nohe/openapi-react-query-codegen/assets/1308309/a6d93131-f81d-478f-9e13-1c3e44f50461)
But path seems off as it does exist in `examples\react-app\petstore.yaml`, so the question is why does it look for it inside `json-schema-ref-parser` instead of the current working directory.

**Comment by AnderssonPeter** [comment]
Adding the following seems to solve the issue
```
  "peerDependencies": {
    "commander": ">= 11 < 13",
    "glob": ">= 10",
    "openapi-typescript-codegen": "^0.24.0",
    "@apidevtools/json-schema-ref-parser": "^11.1.0", <---
    "typescript": ">= 4.8.3"
  }
```

What side effects it would have i don't know.

**Comment by AnderssonPeter** [comment]
@7nohe using https://github.com/nicolas-chaulet/openapi-typescript-codegen instead might solve this issue, and add support for the date type.

**Comment by 7nohe** [comment]
Thank you for the suggestion. I've been considering that relying on external libraries for client code generation might not be ideal, so I am exploring the possibility of creating my own.

**Comment by AnderssonPeter** [comment]
I haven't tested but it should be fairly comparable as it's a fork.

**Comment by AnderssonPeter** [comment]
@7nohe They released a new version of openapi-typescript-codegen 0.28.0 that should resolve the windows issue, but i would still prefer the fork as it handles dates.

**Comment by 7nohe** [comment]
@AnderssonPeter Thank you for letting me know about the new release. I will try upgrading to the new version.

The fork project you told me about seems to have been renamed to [@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts) and is well-maintained, so I'm thinking of switching to it.

**Comment by seriouslag** [comment]
> @AnderssonPeter Thank you for letting me know about the new release. I will try upgrading to the new version.
> 
> The fork project you told me about seems to have been renamed to [@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts) and is well-maintained, so I'm thinking of switching to it.

Opened PR using the [@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts)

**Comment by AnderssonPeter** [comment]
@7nohe are there any plans to enable the https://heyapi.vercel.app/openapi-ts/transformers.html#dates function when `--useDateType` flag is used?

**Comment by 7nohe** [comment]
@AnderssonPeter It looks possible, so I would appreciate it if you could create a new issue.

**Comment by AnderssonPeter** [comment]
@7nohe done #137
