### ISSUE TITLE
Any plans to support `useSuspenseQuery`

### ISSUE THREAD

**Issue by AnderssonPeter** [7nohe/openapi-react-query-codegen#45]
Hi are there any plans to support [useSuspenseQuery](https://tanstack.com/query/v5/docs/framework/react/reference/useSuspenseQuery) for React? it would it easier to use this with [Suspense](https://react.dev/reference/react/Suspense)?

**Comment by seriouslag** [comment]
This should be a relatively straightforward addition to the code to generate both a useQuery hook and a useSuspenseQuery hook.

**Comment by seriouslag** [comment]
We now expose suspense hooks, which can be imported via `/openapi/queries/suspense`

This is documented in the readme, and an example is in the examples folder.

**Comment by seriouslag** [comment]
Re-opening - as this is not yet released.

**Comment by seriouslag** [comment]
@7nohe Would you mind making a release from main with the latest changes?

I would like to start integrating suspense into a project. 😁
