### ISSUE TITLE
Generating from openapi spec on windows causes empty queries index.ts

### ISSUE THREAD

**Issue by mvanvendeloo** [7nohe/openapi-react-query-codegen#5]
My colleague uses WIndows and when he runs the generation process, everything is generated fine, except for the custom part that generates the queries. That file is generated empty, so we are missing the hooks.

**Comment by 7nohe** [comment]
@mvanvendeloo Sorry for the late reply. Did you get any errors when executing the command?
It would be helpful if you could provide details of the environment, such as the Node.js version.

**Comment by mvanvendeloo** [comment]
We do not see any errors in the output. command (using MINGW64):
openapi-rq -i openapi/ui-api.yml -c axios -o src/api/ui

$ npm -version
8.18.0

$ node -v
v14.18.1

**Comment by 7nohe** [comment]
@mvanvendeloo 
I just run [the test](https://github.com/7nohe/openapi-react-query-codegen/actions/runs/3741930860) on three environments and found that only the windows environment is not generating code correctly (the generated file can be downloaded from artifact).
I'm not sure about the reason for that at this time, but I will investigate.
Thanks for your report!

**Comment by mvanvendeloo** [comment]
@7nohe Any luck in finding the issue?

**Comment by 7nohe** [comment]
Sorry, I have been busy with work and have not been able to spend much time here.
I will start the investigation now.

**Comment by 7nohe** [comment]
@mvanvendeloo This issue has been resolved in v0.2.2 🎉

**Comment by mvanvendeloo** [comment]
Super. Thanks!
