### ISSUE TITLE
Request cannot be constructed from a URL that includes credentials

### ISSUE THREAD

**Issue by The-Lone-Druid** [7nohe/openapi-react-query-codegen#63]
$ pnpm run codegen

> hafniapoolparticipantwebapp@0.1.0 codegen C:\Users\zahid\Workspace\invictaworld-workspace\HafniaPoolWeb
> dotenv -e .env.local -- cross-var openapi-rq -i %VITE_SWAGGER_URL% -c axios -o ./src/services/generated

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

JSONParserError: Error downloading https://username:password@pool-participants-web-api-test.azurewebsites.net/swagger/v1/swagger.yaml
Request cannot be constructed from a URL that includes credentials: https://username:password@pool-participants-web-api-test.azurewebsites.net/swagger/v1/swagger.yaml
    at download (C:\Users\zahid\Workspace\invictaworld-workspace\HafniaPoolWeb\node_modules\.pnpm\@apidevtools+json-schema-ref-parser@11.5.4\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\resolvers\http.js:113:15) {
  code: 'ERESOLVER',
  name: 'ResolverError',
  source: 'https://username:password@pool-participants-web-api-test.azurewebsites.net/swagger/v1/swagger.yaml',
  path: null,
  toJSON: [Function: toJSON],
  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
}

Node.js v18.17.1
 ELIFECYCLE  Command failed with exit code 1.
 
 For security purposes, I've replaced the username and password with placeholder values, please look into this issue ASAP.

**Comment by seriouslag** [comment]
Do you have an example we can debug with?
Did this work before version 1.x or is this a new issue?

**Comment by seriouslag** [comment]
I would recommend opening an issue with [@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts) as that package is the generator this tool uses.
The underlying library they use is [json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser)
There may be a different way to pass credentials to that.

**Comment by The-Lone-Druid** [comment]
> Do you have an example we can debug with? Did this work before version 1.x or is this a new issue?

Yes @seriouslag this worked in the previous version and that was [0.5.3](https://www.npmjs.com/package/@7nohe/openapi-react-query-codegen/v/0.5.3), currently to resolve the issue, I've reverted the version and it's working fine now, but it'll be better to use the latest version with this issue fixed.

**Comment by seriouslag** [comment]
We changed the underlying OpenApi generation tool, this won't likely be fixed in a short amount of time if a ticket is not opened in the underlying tools.
