### ISSUE TITLE
Creating empty queries/common/suspense files after v1 upgrade

### ISSUE THREAD

**Issue by spa5k** [7nohe/openapi-react-query-codegen#64]
same as title -

```
  npx --package @7nohe/openapi-react-query-codegen openapi-rq -i ./openapi.yaml -c fetch -o ./apps/web/src/api -c axios

```

Openapi file is correct since it renders correctly on spotlight elements + swagger editor

openapi: 3.1.0

**Comment by seriouslag** [comment]
Please provide minimum spec file, are you using latest version of this package?
What os/node/npm version?

**Comment by spa5k** [comment]
```sh
                   -`                    ree@Windows
                  .o+`                   ----------------------- 
                 `ooo/                   OS: Arch Linux on Windows 10 x86_64 
                `+oooo:                  Kernel: 5.15.146.1-microsoft-standard-WSL2 
               `+oooooo:                 Uptime: 2 mins 
               -+oooooo+:                Packages: 184 (pacman) 
             `/:-:++oooo+:               Shell: zsh 5.9 
            `/++++/+++++++:              Terminal: vscode 
           `/++++++++++++++:             CPU: 11th Gen Intel i7-11800H (16) @ 2.304GHz 
          `/+++ooooooooooooo/`           GPU: f200:00:00.0 Microsoft Corporation Basic Render Driver 
         ./ooosssso++osssssso+`          Memory: 626MiB / 19892MiB 
        .oossssso-````/ossssss+`
       -osssssso.      :ssssssso.                                
      :osssssss/        osssso+++.                               
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/

```

Openapi file - https://gist.github.com/spa5k/e9f687014b377c689a245e8abe41738f

**Comment by seriouslag** [comment]
> ```shell
>                    -`                    ree@Windows
>                   .o+`                   ----------------------- 
>                  `ooo/                   OS: Arch Linux on Windows 10 x86_64 
>                 `+oooo:                  Kernel: 5.15.146.1-microsoft-standard-WSL2 
>                `+oooooo:                 Uptime: 2 mins 
>                -+oooooo+:                Packages: 184 (pacman) 
>              `/:-:++oooo+:               Shell: zsh 5.9 
>             `/++++/+++++++:              Terminal: vscode 
>            `/++++++++++++++:             CPU: 11th Gen Intel i7-11800H (16) @ 2.304GHz 
>           `/+++ooooooooooooo/`           GPU: f200:00:00.0 Microsoft Corporation Basic Render Driver 
>          ./ooosssso++osssssso+`          Memory: 626MiB / 19892MiB 
>         .oossssso-````/ossssss+`
>        -osssssso.      :ssssssso.                                
>       :osssssss/        osssso+++.                               
>      /ossssssss/        +ssssooo/-
>    `/ossssso+/:-        -:/+osssso+-
>   `+sso+:-`                 `.-/+oso:
>  `++:.                           `-/+/
>  .`                                 `/
> ```
> 
> ArchLinux on wsl2 windows 11.
> 
> Openapi file - https://gist.github.com/spa5k/e9f687014b377c689a245e8abe41738f

Not a valid spec file per [editor.swagger.io](https://editor.swagger.io/) or [redocly-cli](https://github.com/Redocly/redocly-cli)

Please address those and try to regenerate API.

**Comment by spa5k** [comment]
yeah seems like there's some problem according to swagger editor with latest api file. need to see whats causing it. Thanks
