### ISSUE TITLE
InitialData Omitted from queries.

### ISSUE THREAD

**Issue by Jakob-Espersen** [7nohe/openapi-react-query-codegen#68]
```
options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn" | "initialData">
```
I have a usecase where initialData from tanStack would be nice to have.
But the generated queries handles queryKey & queryFn, but initialData is not usable?
I have a workaround, but i was wondering why it is. And if there is a recommended way of handling "initialData"

**Comment by seriouslag** [comment]
Hey @Jakob-Espersen, off the top of my head I am not sure why we are omitting initialData.
I have a feeling we did that to make types work. initialData should be of inferred by the passed in value which would be in conflict with the provided <TData> for the override type.

I agree we should add the functionality back in, as we should keep all features of react query.

If you can a PR would be appreciated 😀

**Comment by seriouslag** [comment]
Opened a PR #69 and did a light test, which seems to be okay.

**Comment by seriouslag** [comment]
Released a test version with this patch under: [@seriouslag/openapi-react-query-codegen@next](https://www.npmjs.com/package/@seriouslag/openapi-react-query-codegen/v/next)
