### ISSUE TITLE
Enums flag does not work?

### ISSUE THREAD

**Issue by AnderssonPeter** [7nohe/openapi-react-query-codegen#72]
Hi I'm trying to generate the a enum from the following swagger/openapi definition
```json
"Test": {
  "enum": [
    "Start",
    "Step1",
    "Step2",
    "Step3",
    "Step4"
  ],
  "type": "string"
},
```

But even when i use the `--enums` flag it generates a type instead?
`export type Test = 'Start' | 'Step1' | 'Step2' | 'Step3' | 'Step4';`
I was expecting something like
```
export enum Test {
  START = 'Start',
  STEP1 = 'Step1',
  ....
}
```

I'm running the following command: `cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 openapi-rq --enums -i https://localhost:44353/swagger/v1/swagger.json -o src/openapi/`

**Comment by seriouslag** [comment]
@AnderssonPeter Sorry you are facing an issue, it seems we were not taking in nor passing the correct values to the underlying service generator.

I opened a PR to address this #73

**Comment by AnderssonPeter** [comment]
> @AnderssonPeter Sorry you are facing an issue, it seems we were not taking in nor passing the correct values to the underlying service generator.
> 
> I opened a PR to address this #73 

Dam your quick, no need to be sorry I'm the one that should be thanking you!!

**Comment by seriouslag** [comment]
Released a test version with this patch under: [@seriouslag/openapi-react-query-codegen@next](https://www.npmjs.com/package/@seriouslag/openapi-react-query-codegen/v/next)

**Comment by AnderssonPeter** [comment]
@seriouslag @7nohe Thanks for fixing it, it worked like a charm!!!
