### ISSUE TITLE
Enums are suffixed with Enum?

### ISSUE THREAD

**Issue by AnderssonPeter** [7nohe/openapi-react-query-codegen#89]
**Describe the bug**
All enums that are generated now end with `Enum` this was not the case before.
Are there any flags to disable this?

**To Reproduce**
* Expose a enum in the OpenAPI specification

**Expected behavior**
To not have `Enum` as an suffix.

- OS: Windows 11
- Version 1.2.0

**Comment by seriouslag** [comment]
I don't believe you can disable it as those are generated from the service generator we use @hey-api/openapi-ts

Opening an issue in that project may be helpful.

I personally would recommend against using typescript enums in general. 

[https://dev.to/ivanzm123/dont-use-enums-in-typescript-they-are-very-dangerous-57bh](https://dev.to/ivanzm123/dont-use-enums-in-typescript-they-are-very-dangerous-57bh)

**Comment by AnderssonPeter** [comment]
I'm faily certain that 1.1.0 did not have this issue (the output in #85 indicates that this is correct)
But i can see that the `@hey-api/openapi-ts` was upgraded to 0.42.1, but i will create a issue over there.

**Comment by AnderssonPeter** [comment]
https://github.com/hey-api/openapi-ts/issues/491

**Comment by AnderssonPeter** [comment]
@seriouslag it looks like [@hey-api/openapi-ts@0.43.0](https://github.com/hey-api/openapi-ts/releases/tag/%40hey-api%2Fopenapi-ts%400.43.0) solved this issue, any chance you could upgrade?

**Comment by seriouslag** [comment]
Updated to 0.43.0 in latest.

**Comment by AnderssonPeter** [comment]
Thanks for your fast response, it works like a charm!!
