### ISSUE TITLE
Dynamic base url using env vars

### ISSUE THREAD

**Issue by nopitown** [7nohe/openapi-react-query-codegen#90]
**Is your feature request related to a problem? Please describe.**
Currently, I'm unable to use a dynamic base for the URLs. In production webs, urls might differ from those in dev environments. I saw that we have a `--base` option, but it seems that only a string can be sent.

**Describe the solution you'd like**
Make --base more flexible so it can also accept env vars. This is currently possible if [we modify the OpenAPI config](https://github.com/hey-api/openapi-ts/issues/368#issuecomment-2051374787)

**Describe alternatives you've considered**
I also considered using the new interceptor feature, but it isn't possible to modify the URL.

**Additional context**
This feature would be really good in order to be able to prefetch queries in server components as fetch calls doesn't accept relative paths.

**Comment by seriouslag** [comment]
@nopitown,

Modifying the OpenAPI config sounds precisely like what you need.

Changing the `BASE` URL option on the OpenAPI config before 

Import the constant into your runtime and modify it before setting up the react app.

```typescript
/** main.tsx */
import { OpenAPI as OpenAPIConfig } from './openapi/requests/core/OpenAPI';
...
OpenAPIConfig.BASE = 'www.domain.com/api';
OpenAPIConfig.HEADERS = {
  'X-Header1': 'header-1'
  'X-Header2': 'header-2'
};
...
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </React.StrictMode>
);

```

**Comment by nopitown** [comment]
Oh! I didn't know I was able to override it like that. I'll try it out!

**Comment by nopitown** [comment]
It does work as expected! I guess it is just a matter to document it in a FAQ. Thank you so much for the help!

**Comment by seriouslag** [comment]
Opened PR #88 to add info in readme.
