### ISSUE TITLE
Helpers to prefetch data 

### ISSUE THREAD

**Issue by nopitown** [7nohe/openapi-react-query-codegen#91]
**Is your feature request related to a problem? Please describe.**
Currently, I'm prefetching data in a server component so it can later be used in a client component. But creating the code is a manual process that could be easier if we have helpers (similar to the hooks). 

**Describe the solution you'd like**

It would be nice to have something like:
```ts
await useFooServiceFindOnePrefetch(//...keys); // or await prefetchFooServiceFindOne(//...keys)
```

Instead of building it from scratch:
```ts
  await queryClient.prefetchQuery({
    queryKey: [
      useFooServiceFindOnePrefetchKey,
     // more keys
    ],
    queryFn: () => {
      return FooService.findOne(//...keys);
    },
  });
```

Any chance to consider this?
**Describe alternatives you've considered**
N/A

**Additional context**
I'm prefetching data using the guidelines from [here](https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr#prefetching-and-dehydrating-data)

**Comment by seriouslag** [comment]
@nopitown, thank you for the suggestion!
It does feel like we could generate these.

I have not used prefetch with tanstack before.

We would need the user to pass the queryClient to each method.

My understanding this is only for GET requests.


My rough draft of what the generated code should look like and how to use it.
```typescript
const useFooServiceFindOnePrefetch = (queryClient: QueryClient, options = {
  // properties here
}) => queryClient.prefetchQuery({
  queryKey: [
    useFooServiceFindOnePrefetchKey,
    // options
  ],
  queryFn: () => {
      return FooService.findOne({
        // options
      });
    },
});


const queryClient = new QueryClient({});
await useFooServiceFindOnePrefetch(queryClient);
```

**Comment by nopitown** [comment]
This looks fantastic! Let me give it a try 🙏🏼

**Comment by seriouslag** [comment]
Reopening as this is not released yet. @7nohe

**Comment by 7nohe** [comment]
Sorry for the delay. v1.2.1 has been released!

**Comment by nopitown** [comment]
Posted something that could make the hook more useful https://github.com/7nohe/openapi-react-query-codegen/issues/102
